### ISSUE TITLE
Add `OperationResult a` to Benchmark.LowLevel

### ISSUE THREAD

**Issue by s6o** [BrianHicks/elm-benchmark#22]
This assumes 1.0.2 source.

## Why
For one of timings of a function where in addition to execution time the function's result should also be captured.

In addition to:
```
Benchmark.LowLevel.sample : Int -> Operation -> Task Error Time
```

there could be also:
```
Benchmark.LowLevel.sampleResult : Int -> OperationResult a -> Task Error (a, Time)
```

In case of sample sizes > 1 the last result (or first) would be taken, given that inputs are always the same it would not make sense to collect all results into a list, as the would all be the same.

or given that this a one of thing perhaps
```
Benchmark.LowLevel.sampleResult : OperationResult a -> Task Error (a, Time)
```
instead, where sample size is 1.

## Background
I've been porting Simplify.js and working on a demo site similar to the original project, I've found that is actually not possible to get a simple measurement of duration with a result.

I can of course use Task and do something like:
```
simplifyCmd : PixelTolerance -> Quality -> List (Float, Float) -> Cmd Msg
simplifyCmd pxlt q points =
  Task.perform Measure <|
    ( Time.now
      |> Task.andThen (\t1 ->
        Task.map2 (\spoints t2 -> (spoints, t2 - t1))
          (S.simplify pxlt q points |> Task.succeed)
          Time.now
      )
```
  
but this looks to be rather inaccurate and a simple test with Benchmark.LowLevel.sample and the above puts the difference on my setup around 1.5x

## Links

  * [elm-simplify demo website]( https://s6o.github.io/elm-simplify/)
  * [elm-benchmark and task timing comparison](https://github.com/s6o/elm-simplify/blob/master/benchmark/Main.elm)

**Comment by BrianHicks** [comment]
Hi! Thanks for opening this! I've wondered how to support it for some time but never wrote it down. 

The short version is that I'm unlikely to support what you want in this library. Timing an individual function has some problems, and it's a core library concern.

That said, we will have to make some changes to support Elm 0.19, and we'll see if including something like this makes sense long-term. Your example really helps move that along. Watch #20 for progress updates. 

I'm going to leave this issue open to keep it in mind in the future. I don't want to discourage you here; I hope we can solve for your use case! It just may not be here *per se*.

**Comment by zwilias** [comment]
I think that, due to the very nature of JS and the way optimizations work in browsers, a single run is simply not measurably accurately; and the best you can do is get an upper bound.

For example on the `elm-simplify` page, when it loads I get ~100ms for 0.8. Moving the slider along, then putting it back at 0.8 gives me ~20ms. There's no memoization or any such thing happening, it's just the browser optimizing functions and a different workload happening in the browser so more resources may be available after a pageload as compared to "during" a pageload.

The long and short of it: exposing a way to do a single run with a high-accuracy timer would be misleading at best. The timing will be highly accurate, but wouldn't say much about the performance of a function, other than a vague upper bound.

**Comment by BrianHicks** [comment]
That's a really good point, @zwilias!

@s6o maybe instead of doing this, you could publish your benchmarking code and results? It'd be a far more reliable way to indicate the level of performance you can provide.

**Comment by BrianHicks** [comment]
Closing this to clean up issues to get the next version shipped. @s6o, hope the approach mentioned above works for you. LMK if you have any problems with it, happy to help.
