### ISSUE TITLE
CLI helper (request for review)

### ISSUE THREAD

**Issue by ymtszw** [BrianHicks/elm-benchmark#38]
Hi, I like elm-benchmark and started using in my projects!

One thing I found cumbersome is it currently does not have CLI helper like `elm-test` does.
Here I'm not talking about CLI benchmark runner, (which would be cool too though,)
rather talking about convenient bootstrap tool that prepares benchmark application stub.
Similarly to what `elm-test init` does.

And I thought I could make one 😄 

[ymtszw/elm-benchmark-helper](https://github.com/ymtszw/elm-benchmark-helper)

It is `npm install`-able tool that has node script `elm-benchmark`.
It will:

- with `init` subcommand,
    - create `benchmarks/` dir
    - read your `elm-package.json` and generate `benchmarks/elm-package.json`
    - generate stub benchmark application in `benchmarks/Benchmarks.elm`
- with `compile` subcommand,
    - compiles `benchmarks/Benchmarks.elm` into specified target (defaults to `docs/index.html`)

It would be cool if you would give it a review!
It is yet to be published to `npm`, but if you do not mind me to do so, I will :)

Thanks in advance!

**Comment by BrianHicks** [comment]
wow, this is great timing! I'm just starting to plan out the work for a CLI runner in general. This was one of the "stretch" features I wanted, and you've already done it! Are you a mind-reader?

If you don't mind, could we do something different? If you're OK licensing under BSD-3, do you think you could take your work here and open a PR against this repo? I'd love to build on this!

**Comment by ymtszw** [comment]
Actually it's THE better half of my expectation if you adopt my work under this repo 😆 
So,

>  do you think you could take your work here and open a PR against this repo?

I'm wholeheartedly positive about this! And I'm fine with BSD3.

Just let me take some time to merge my work into the fork of this repo.

Also, please give some review on PR and/or do some refinement before npm publication:

- make sure it properly works (obviously) since I'm not giving it a thorough test
    - at least it's working with my own package => https://github.com/ymtszw/elm-xml-decode
- decide how to organize Elm part and node script part; whether split them in different repository (like `elm-test` doing with `node-test-runner` repo) or not
- how to access `elm-make`; currently my code is simply accessing `elm-make` binary via `child_process.execSync`, though `elm-test` is doing it via `node-elm-compiler`
    - I personally think whichever is fine, and I'm not so certain how to properly use `node-elm-compiler`'s APIs 😝 

I believe you are already giving some thoughts on portions of these, though.

Anyway, thanks for your proposal!
Wait for me to drop a PR.

**Comment by BrianHicks** [comment]
Yep! Here are my thoughts:

- thanks for doing testing, although I'm sure we'll do plenty more!
- they should be in this repo. I'd prefer they be under `cli` if possible. If that's not possible, a root `package.json` is not the end of the world. All the first-party runners are going to live in this repository.
- don't worry about the compile step too much. We can probably end up putting this command at `compile-web` or something. There's a lot more machinery that we need to do a proper CLI. We'll probably end up using `node-elm-compiler`.

When you make your PR, could you make it against the `cli` branch instead of `master`? I'd like to keep this work separate until it's done so that I can release bug fixes for the 2.x line.

**Comment by ymtszw** [comment]
PR #40 on the way! Against `cli` branch.
Please take a look ;)
